[core|hub] User login with Google-auth (backend)            https://trello.com/c/FLsTryS4
[core]
  * making request to google+ api with oauth2 access token
  * gets profile & email from google on authentication
  * get mysql connection provider
  * run flyway migrations on app start
  * design architecture of models, static fetch method
  * controllers
  * core migrations
  * figured out basic jOOQ API
  * test for util; enhanced implementation
  * misc. tests for auth components
  * store access tokens in redis as hash maps for access control layer
  * server access log to file only, not stderr
  * AccessControlFilter intercepts all requests
  * user_role migration

[hub]
  * full implementation of google auth, creates auth'd session

[workflow]
  * docker create mysql db if not exists
  * script bin/props lists io.outright.xj.core.app.config.Config properties

diff --git a/.docker/bin/boot-docker b/.docker/bin/boot-docker
--- a/.docker/bin/boot-docker
+++ b/.docker/bin/boot-docker
@@ -17,6 +17,24 @@ mysql_ok () {
   fi
 }
 #
+mysql_create_database () {
+  HOST="${1}"
+  PORT="${2}"
+  NAME="${3}"
+  if mysql \
+    -h "${HOST}" \
+    -P "${PORT}" \
+    -uroot \
+    --connect-timeout=1 \
+    -e "create database if not exists ${NAME};"; then
+    echo "Created MySQL database ${NAME}"
+    return 0
+  else
+    echo "Failed to create MySQL database ${NAME}"
+    return 1
+  fi
+}
+#
 redis_ok () {
   HOST="${1}"
   PORT="${2}"
@@ -46,6 +64,11 @@ printf "\n[xj:docker]\n"
 #
 wait_until "mysql_ok mysql01er1 3306"
 wait_until "redis_ok redis01er1 6379"
+
+#
+if ! mysql_create_database mysql01er1 3306 xj; then
+  exit 1
+fi
 
 # serve static frontend with nginx
 chmod -R +r /var/app/current/ui/dist
diff --git a/bin/props b/bin/props
--- a/bin/props
+++ b/bin/props
@@ -12,10 +12,22 @@ indent "${APPS}"
 step_ok
 
 #
-step "System properties:"
+step "Searching for loose system properties"
 for APP in ${APPS}; do
-  ack-grep --ignore-file='match:/Test.java/' --heading --color -o 'System.getProperty\(\"([^\"]+)\"' ${PWD}/${APP} | sed 's/System.getProperty(//g'
+  if ack-grep --ignore-file='match:/Test.java/' \
+              --ignore-file='match:/Config.java/' \
+              --heading --color -o \
+              'System.getProperty\(([^\)]+)\)' \
+              ${PWD}/${APP}; then
+    printf "\n${RED}ERROR!${RESET}\nPlease ensure that all app configuration implements ${GREEN}io.outright.xj.core.app.config${RESET}.\nThere should be no loose System.getProperty().\n\n"
+    exit 1
+  fi
 done
+step_ok
+
+#
+step "io.outright.xj.core.app.config.Config properties:"
+indent "$(grep -oE "\"[a-z]+\.[a-z\.]+\"" core/src/main/java/io/outright/xj/core/app/config/Config.java)"
 step_ok
 
 #
