[xj:workflow] refactoring bin to .z. so not-package-namespace! so unique! so easy to type! and tweaking docker-compose workflow

diff --git a/.docker/internal/boot b/.docker/internal/boot
--- a/.docker/internal/boot
+++ b/.docker/internal/boot
@@ -2,8 +2,13 @@
 
 bg_java_app() {
   APP=${1}
+  JAR=/var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar
+  if [ -n ${JAR} ]; then
+    printf "\n\nCan't find ${JAR}!\nPlease package the build artifacts.\n\n"
+    exit 1
+  fi
   mkdir -p /var/log/${APP}
-  java -jar /var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar &>/var/log/${APP}/${APP}.log &
+  java -jar ${JAR} &>/var/log/${APP}/${APP}.log &
   printf "Starting java: /var/app/current/${APP}/target/${APP}-1.0-SNAPSHOT.jar >>> /var/log/${APP}/${APP}.log\n"
 }
 
