Workstation GUI .jar distribution (#10)
- Github actions gets version from gradle.properties, builds and extracts shadow dist, then uploads the folder as artifact
- CI tag release ensures that gradle.properties version number matches tag name

XJ music workstation (basic)
https://www.pivotaltracker.com/story/show/185754555

diff --git a/.github/workflows/tag_dist.yml b/.github/workflows/tag_dist.yml
--- a/.github/workflows/tag_dist.yml
+++ b/.github/workflows/tag_dist.yml
@@ -5,6 +5,26 @@ on:
     tags: ['*']
 
 jobs:
+  version:
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.get-version.outputs.version }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Get version from gradle.properties
+        id: get-version
+        run: |
+          VERSION=$(grep "version=" gradle.properties | sed -n -e 's/^.*version=//p')
+          if [ -z "$VERSION" ]; then
+            echo "Version number not found!"
+            exit 1
+          fi
+          echo "Version is $VERSION"
+          echo "version=$VERSION" >> $GITHUB_ENV
+          echo "::set-output name=version::$VERSION"
+
   distribute_service:
     env:
       REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
@@ -66,6 +86,44 @@ jobs:
             -PjibToTags=${{  github.ref_name }} \
             :service:jib
         continue-on-error: false
+
+  distribute_gui_shadow_jar:
+    needs: version
+    name: Distribute GUI shadow distribution
+    env:
+      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
+      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
+      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    permissions: write-all
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Git checkout
+        uses: actions/checkout@v2
+
+      - name: Set up JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: 18
+
+      - name: Echo JAVA_HOME
+        run: echo $JAVA_HOME
+
+      - name: Verify Gradle Wrapper
+        uses: gradle/wrapper-validation-action@v1
+
+      - name: Execute build of GUI shadow zip
+        run: ./gradlew --info --stacktrace :gui:shadowDistZip
+
+      - name: Extract the contents of the shadow zip
+        run: unzip -o gui/build/distributions/gui-shadow-${{ needs.version.outputs.version }}.zip -d gui/build/distributions/
+
+      - name: Upload GUI Shadow distribution as an artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: xjmusic-workstation-shadow-dist
+          path: gui/build/distributions/gui-shadow-${{ needs.version.outputs.version }}/
 
   distribute_gui:
     name: Distribute ${{ matrix.os }} JDK ${{ matrix.java }}
